### ISSUE TITLE
Rounding issue

### ISSUE THREAD

**Issue by shlima** [ERPedersen/vue-units#4]
Hello, Thank you for you package.

I have rounding issue: I convert 73251 meters to miles using the following code:

```js
{{ 74521 | units('m', 'mi', true) }}
```

The result I've got is: `45.516062659090906 mi`

Could you please add rounding option to the filter, please ?

**Comment by JoeEarly** [comment]
@ERPedersen any thoughts on this as just came across it myself going from ft to mts and vice versa
